# Generated by Django 4.2.6 on 2023-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_created',
            field=models.DateTimeField(default='2021-12-12 11:44:59'),
        ),
    ]
