# Generated by Django 4.2.6 on 2023-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_token_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
