# Generated by Django 4.2.6 on 2023-10-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_is_taken_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(to='donations.category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='donations.category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('3', 'zbiórka lokalna'), ('1', 'fundacja'), ('2', 'organizacja pozarządowa')], default=1, max_length=64),
        ),
    ]
