# Generated by Django 4.2.6 on 2023-10-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_it_on_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1, max_length=64)),
                ('categories', models.ManyToManyField(to='pass_it_on_app.category')),
            ],
        ),
    ]
