# Generated by Django 4.2.6 on 2023-10-15 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_it_on_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi zawierać od 9 do 15 cyfr.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Kod pocztowy musi być podany w formacie 12345 lub 12-345', regex='^(\\d{2}(?:[-]\\d{3})|\\d{5})$')]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[(2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna'), (1, 'fundacja')], default=1, max_length=64),
        ),
    ]
