# Generated by Django 4.2.6 on 2023-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_it_on_app', '0004_alter_donation_phone_number_alter_donation_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(null=True),
        ),
    ]
