# Generated by Django 4.2.6 on 2023-10-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_it_on_app', '0006_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('3', 'zbiórka lokalna'), ('2', 'organizacja pozarządowa'), ('1', 'fundacja')], default=1, max_length=64),
        ),
    ]
